### ISSUE TITLE
No definition shown on OSX VSC

### ISSUE THREAD

**Issue by drleidig** [faubulous/mentor-vscode#40]
FIrst I have to say that this could be a very helpful extension for editing larger vocabulary files.
I was looking for something similar for quite a while.

However, it does not seem to work on my MacBook.

The vocab is shown in the sidebar but no definitions.
Also no lens annotations.
What does "No file selected" mean? Do I miss something.
<img width="1612" alt="Bildschirmfoto 2024-10-15 um 12 44 39" src="https://github.com/user-attachments/assets/f5fe6276-f6bd-4dcf-9d0c-294a9622718d">

**Comment by faubulous** [comment]
Thank you @drleidig for reporting this issue. From what I can see, I suspect that the definitions do not appear because there is no owl:Ontology header defined in the file. Please check this out and let me know if other vocabularies work for you.

If this is the case, then the bug is that when the display of the definitions is set to 'Group by Source of Definition', then the list is empty instead of showing everything under an anonymous / unkown group. This should not be hard to fix.

![image](https://github.com/user-attachments/assets/45cea72d-410f-4a19-90a9-75384bb69c3f)

Does 'Group by Type' work for you? Since this is foaf, would you be able to share the file? There are mulitple versions circulating out there..

**Comment by faubulous** [comment]
What is strange indeed is that there are no lenses appearing. This in combination with the 'No file selected' might indicate that this is actually caused by something else. Maybe another extension..
